**(1)**

In [ ]:
import numpy as np

# Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange its rows and columns using the transpose method
transposed_array = array.T

print("Original Array:")
print(array)
print("\nTransposed Array (Rows and Columns Interchanged):")
print(transposed_array)


Original Array:
[[ 8 33 37]
 [82 37 92]
 [39 34 96]]

Transposed Array (Rows and Columns Interchanged):
[[ 8 82 39]
 [33 37 34]
 [37 92 96]]


**(2)**

In [ ]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(1, 11)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)


1D Array:
[ 1  2  3  4  5  6  7  8  9 10]

2x5 Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

5x2 Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


**(3)**

In [ ]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 Array:")
print(array_4x4)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


Original 4x4 Array:
[[0.06062696 0.99987588 0.6225243  0.85466292]
 [0.92344438 0.12646698 0.57001486 0.98042982]
 [0.59749804 0.79712382 0.11070266 0.9892873 ]
 [0.72770595 0.1397694  0.02455903 0.44170222]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.06062696 0.99987588 0.6225243  0.85466292 0.        ]
 [0.         0.92344438 0.12646698 0.57001486 0.98042982 0.        ]
 [0.         0.59749804 0.79712382 0.11070266 0.9892873  0.        ]
 [0.         0.72770595 0.1397694  0.02455903 0.44170222 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**(4)**

In [ ]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array_integers = np.arange(10, 61, 5)

print(array_integers)


[10 15 20 25 30 35 40 45 50 55 60]


**(5)**

In [ ]:
import numpy as np

# Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array_strings)        # Uppercase
lowercase = np.char.lower(array_strings)        # Lowercase
titlecase = np.char.title(array_strings)        # Title case
capitalize = np.char.capitalize(array_strings)  # Capitalized first letter

# Display the results
print("Original Array:")
print(array_strings)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(titlecase)
print("\nCapitalized:")
print(capitalize)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


**(6)**

In [ ]:
import numpy as np

# Create a NumPy array of words
array_words = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', array_words)

# Display the result
print("Original Array:")
print(array_words)
print("\nArray with Spaces Between Characters:")
print(spaced_words)


Original Array:
['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


**(7)**

In [ ]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition
addition = array1 + array2

# Perform element-wise subtraction
subtraction = array1 - array2

# Perform element-wise multiplication
multiplication = array1 * array2

# Perform element-wise division
division = array1 / array2

# Display the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


**(8)**

In [ ]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

# Display the results
print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


**(9)**

In [ ]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display the results
print("Random Integers Array:")
print(random_integers)
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers Array:
[368 150 735 834 148 386 539 621 640 864 293 318 570 323 951  43 315 914
 353 319 522 749 715  38 165 778 274 930 294 846 820 955 556 952 803 914
 909 530  84 320 973 682  67 857 276 999 297 785 966 686 978 715 778  98
 580 727 773  45 651 145 328 714 996 624 155 756 576 936 533 522  82 951
  59 599   1 447 527 332 632 982 298 934 973 756  69 471 654  40 522 881
 192 197 567 182 433 985 693 240  34 567]

Prime Numbers in the Array:
[293, 43, 353, 67, 857, 727, 773, 59, 599, 881, 197, 433]


**(10)**

In [12]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For demonstration, we'll generate random temperatures between 15 and 35 degrees Celsius
daily_temperatures = np.random.randint(15, 36, size=30)

# Reshape the first 28 days into a 4-week format (4 rows for 4 weeks, 7 columns for 7 days)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate the weekly averages for the first 4 weeks
weekly_averages = np.mean(weekly_temperatures, axis=1)

# For the last week with only 2 days, extract those temperatures
last_week_temperatures = daily_temperatures[28:]

# Display the results
print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Temperatures (4 Complete Weeks):")
print(weekly_temperatures)
print("\nWeekly Averages for 4 Complete Weeks:")
print(weekly_averages)
print("\nLast Week's Temperatures (2 days):")
print(last_week_temperatures)


Daily Temperatures for the Month:
[35 34 35 25 29 22 25 22 25 15 16 20 26 35 30 22 25 16 32 20 29 20 21 26
 33 21 16 28 34 29]

Weekly Temperatures (4 Complete Weeks):
[[35 34 35 25 29 22 25]
 [22 25 15 16 20 26 35]
 [30 22 25 16 32 20 29]
 [20 21 26 33 21 16 28]]

Weekly Averages for 4 Complete Weeks:
[29.28571429 22.71428571 24.85714286 23.57142857]

Last Week's Temperatures (2 days):
[34 29]
